name: Lint / Test / Build

on:
  pull_request:
  push:
    branch: BM-6-proxy-setup-for-app-frontend

env:
  DEFAULT_NODE_VERSION: 20 # FIXME use nvmrc instead

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.action }} (${{ matrix.node-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22]
        action: [build, lint] # , test]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - name: ci:${{ matrix.action }}
        shell: bash
        run: npm run ci:${{ matrix.action }}
        env:
          GITHASH: ${{ github.sha }}
          GITHUB_REPO: ${{ github.repository }}
          BASE_BRANCH: ${{ github.base_ref || 'bm-develop' }}
          NODE_VERSION: ${{ matrix.node-version }}

      - name: 'Android testing: Setup Java'
        if: matrix.action == 'build'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23 # required for this version of Gradle
          cache: gradle

      - name: 'Android testing: Setup Gradle'
        if: matrix.action == 'build'
        uses: gradle/actions/setup-gradle@v5

      - name: 'Android testing: Run tests'
        if: matrix.action == 'build'
        run: |
          cd android
          ./gradlew :proxy-networking:testDebugUnitTest
